(rule (can-replace-job ?person-1 ?person-2)
      (or
       (and (job ?person-1 ?job-1)
	    (job ?person-2 ?job-2)
	    (same ?job-1 ?job-2)
	    (not (same ?person-1 ?person-2)))
       (and (job ?person-1 ?job-1)
	    (job ?person-2 ?job-2)
	    (can-do-job ?job-1 ?job-2)
	    (not (same ?person-1 ?person-2)))))

(can-replace-job ?x (Fect Cy D))
(and (can-replace-job ?person-1 ?person-2)
     (salary ?person-1 ?salary-1)
     (salary ?person-2 ?salary-2)
     (lisp-value < ?salary-1 ?salary-2))