(define (init-random) 3)
(define (rand-update x) (+ x 1))
(define rand (let ((x (init-random)))
	       (lambda (m)
		 (cond ((eq? m 'generate)
			(set! x (rand-update x))
			x)
		       ((eq? m 'reset)
			(lambda (init-x)
			  (set! x init-x)
			  x))
		       (else (error "Unknown request: RAND" m))))))

((rand 'reset) 2)
(rand 'generate)