(define (eval exp env)
  (cond ((unless? exp) (eval (unless->if exp) env))))

(define (unless? exp) (tagged-list? exp 'unless))
(define (unless-predicate exp) (cadr exp))
(define (unless-usual-value exp) (caddr exp))
(define (unless-exceptional exp)
  (if (not (null? (cdddr exp)))
      (cadddr exp)
      false))
(define (unless->if exp)
  (make-if (unless-predicate exp)
	   (unless-exceptional-value exp)
	   (unless-usual-value exp)))