(define (get-register machine register-name)
  ((machine 'get-register) register-name))
(define (get-operation-proc machine op-name)
  ((machine 'lookup-operation) op-name))
(define (lookup-label-insts machine label-name)
  ((machine 'lookup-label) label-name))

(define (advance-pc machine)
  (machine 'advance-pc))
(define (advance-pc-to machine insts)
  ((machine 'advance-pc-to) insts))

(define (get-stack machine)
  (machine 'get-stack))
(define (get-stack-contents machine)
  (let ((stack (get-stack machine)))
    (stack 'get-contents)))
(define (push-stack machine value)
  (let ((stack (get-stack machine)))
    ((stack 'push) value)))
(define (pop-stack machine)
  (let ((stack (get-stack machine)))
    (stack 'pop)))