(define (make-unbound! var env)
  (let ((frame (first-frame env)))
    (define (scan vars vals)
      (cond ((null? vars)
	     (error "Unbound variable: UNBOUND!" var))
	    ((eq? var (car vars)) (cdr vals))
	    (else (cons (car vals)
			(scan (cdr vars) (cdr vals))))))
    (scan (frame-variables frame) (frame-values frame))
    (set! (frame-variables frame)
	  (filter (lambda (frame-var) (eq? frame-var var))
		  (frame-variables frame)))))