(define (make-stack)
  (let ((stack '()))
    (define (push value)
      (set! stack (cons value stack)))
    (define (pop)
      (if (null? stack)
	  (error "STACK is empty")
	  (let ((value (car stack)))
	    (set! stack (cdr stack))
	    value)))
    (define (dispatch message)
      (cond ((eq? message 'push) push)
	    ((eq? message 'pop) (pop))
	    ((eq? message 'get-contents) stack)
	    (else
	     (error "Unknown request type: STACK" message))))
    dispatch))